### PR TITLE
Adapt to changes in Coordinate class in product

### PR DESCRIPTION
**Pull request by MishaDemianenko**

### CODE REVIEW

**Review by AzuObs — APPROVED** [review]

**Review by ncordon — COMMENTED** [review]
I'm unsure whether this would pass the spotless check we have. Can you run `./gradlew spotlessApply` and then re-commit if there are any changes?

Otherwise looks good

**Comment by MishaDemianenko** [comment]
> ./gradlew spotlessApply

looks happy with current formatting and no changes made on local env as result of that

**Review by ncordon — CHANGES_REQUESTED** [review]
This needs to be pushed to the repo directly, not to a fork

**Comment by MishaDemianenko** [comment]
> This needs to be pushed to the repo directly, not to a fork

why?

**Comment by ncordon** [comment]
> This needs to be pushed to the repo directly, not to a fork

Because the CI secrets are only available in branches in the repo and it will not be able to download in-dev neo4j artifacts in forks

**Pull request closed without merging**
