### PR TITLE
[gRNAet7B] Changed trigger descriptions

### PR DESCRIPTION
**Pull request by vga91**
Changed trigger descriptions to be consistent with docs pr: https://github.com/neo4j/docs-apoc/pull/83

### CODE REVIEW

**Review by AzuObs — APPROVED** [review]
LGTM. Thanks for taking care of it.

**Review by AzuObs — CHANGES_REQUESTED** [review]
This particular change is great. However, I noticed that the @Procedure annotation are missing the "name" param for all of our new triggers. I think Gem put some effort into making this consistent a few months ago, sorry for missing that before.

Example of what I mean `@Procedure(name = "apoc.trigger.drop, mode = Mode.WRITE)`

**Comment by vga91** [comment]
Oh I see. Ok no problem, just added params as well 

> This particular change is great. However, I noticed that the @procedure annotation are missing the "name" param for all of our new triggers. I think Gem put some effort into making this consistent a few months ago, sorry for missing that before. Example of what I mean `@Procedure(name = "apoc.trigger.drop, mode = Mode.WRITE)`
> 
> Would you mind making updates the annotations as part of this PR?

**Review by AzuObs — APPROVED** [review]
LGTM, thank you for accepting the additional request 👍

**Pull request merged**
