### PR TITLE
[yaWCMgIP] Exclude asm to fix startup issue

### PR DESCRIPTION
**Pull request by gem-neo4j**
I tested this manually by copying the jar to desktop and changing the name to: apoc5plus-5.15.0, without this change it fails, with it works (also with it, there is no trace of it in the logs either)

### CODE REVIEW

**Review by ncordon — CHANGES_REQUESTED** [review]
Are we sure the dependency is `asm` is included in neo4j? 

What kernel said in their messages is that it was included in the `neo4j-jwt-addon.jar` plugin, which is not always present (in Desktop it seems it always is).

For this to work and not cause binary incompatibility issues on runtime we need to be sure `asm` is shipped with the community projects of neo4j.

**Comment by gem-neo4j** [comment]
I think so, what I did was I checked the dependencies in APOC, and it was listed under org.neo4j:neo4j-codegen:5.16.0-SNAPSHOT, org.neo4j:test-utils:5.16.0-SNAPSHOT as well, and the POM in codegen for example was:

```
                <configuration>
                    <artifactSet>
                        <includes>
                            <include>org.ow2.asm:*</include>
                        </includes>
                    </artifactSet>
                    <relocations>
                        <relocation>
                            <pattern>org.objectweb.asm</pattern>
                            <shadedPattern>org.neo4j.codegen.asm</shadedPattern>
                        </relocation>
                    </relocations>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                </configuration>
```

I assumed include here implies it is shipped with Neo. Is there another way I can check?

**Comment by neo-technology-build-agent** [comment]
:x: [generateLicenses failed][1]

[1]: https://github.com/neo4j/apoc/actions/runs/7420272863

**Review by ncordon — APPROVED** [review]

**Pull request merged**
