### PR TITLE
Fix the missing constraint error message for apoc.import.json()

### LINKED ISSUE #290: The missing constraint error message for apoc.import.json() is incorrect
## Expected Behavior (Mandatory)

When executing `apoc.import.json()`, an error message for missing constraints might pop up and suggests a correct query to create the constraint.

## Actual Behavior (Mandatory)

The query suggested is incorrect and will not execute successfully.

### Steps (Mandatory)

  1. Run `apoc.import.json("sample.json");`
  1. See the error message that contains a suggested query: `CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS UNIQUE`
  1. Run the above query
  1. It shows `Invalid constraint syntax, ON and ASSERT should not be used. Replace ON with FOR and ASSERT with REQUIRE.`

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOS 12.4
  - Neo4j: 5.3.0
  - Neo4j-Apoc: 5.3.0

### PR DESCRIPTION
**Pull request by johnlinp**
Fixes #290

Signed-off-by: John Lin <johnlinp@gmail.com>

## Proposed Changes (Mandatory)

Use `FOR` instead of `ON` and use `REQUIRE` instead of `ASSERT`.

### CODE REVIEW

**Comment by AzuObs** [comment]
Hi @johnlinp,

Thank you so much for offering this pull request. The code change you'd like to make seems like a valuable change to me! However, in order to accept your pull request I would need you to first accept our contributor license agreement. This process for doing so can be found at https://neo4j.com/developer/cla/.

Please let me know once you've sent the email and I will approve this request.

**Review by AzuObs — CHANGES_REQUESTED** [review]
Hi @johnlinp,

Thank you so much for offering this pull request. The code change you'd like to make seems like a valuable change to me! However, in order to accept your pull request I would need you to first accept our contributor license agreement. This process for doing so can be found at https://neo4j.com/developer/cla/.

Please let me know once you've sent the email and I will approve this pull request.

**Comment by johnlinp** [comment]
Thanks for the reminder. I've sent the email.

**Comment by AzuObs** [comment]
Closing this PR in favour of https://github.com/neo4j/apoc/pull/304. I hope this is OK with you.

**Pull request closed without merging**
